### ISSUE TITLE
 Cannot install plugin with cordova 8

### ISSUE THREAD

**Issue by sinedied** [homerours/cordova-music-controls-plugin#131]
Whenever I try to install this plugin with Cordova 8 / cordova-android@7.1.0, I get this error:
```
Failed to install 'cordova-plugin-music-controls': Error: Unable to graft xml at selector "/manifest/application" from "/Users/noda/projects/hadra-trance-festival/platforms/android/app/src/main/res/xml/config.xml" during config install
    at ConfigFile_graft_child [as graft_child] (/Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigFile.js:120:19)
    at PlatformMunger_apply_file_munge [as apply_file_munge] (/Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:83:34)
    at munge_helper (/Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:238:14)
    at PlatformMunger.add_plugin_changes (/Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/cordova-common/src/ConfigChanges/ConfigChanges.js:164:12)
    at /Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/cordova-common/src/PluginManager.js:126:25
    at _fulfilled (/Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/q/q.js:854:54)
    at self.promiseDispatch.done (/Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/q/q.js:883:30)
    at Promise.promise.promiseDispatch (/Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/q/q.js:816:13)
    at /Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/q/q.js:877:14
    at runSingle (/Users/noda/projects/hadra-trance-festival/platforms/android/cordova/node_modules/q/q.js:137:13)
Failed to restore plugin "cordova-plugin-music-controls" from config.xml. You might need to try adding it again. Error: Error: Unable to graft xml at selector "/manifest/application" from "/Users/noda/projects/hadra-trance-festival/platforms/android/app/src/main/res/xml/config.xml" during config install
```
Any ideas?

**Comment by cnttech** [comment]
i have same problem with cordova 8.0.0

**Comment by fdambrosio** [comment]
there's a workaround?

**Comment by sinedied** [comment]
@fdambrosio  I reverted to cordova 7.1.0 and cordova-android 6.4.0 to make it work, but no workaround for updated versions.

**Comment by lethak** [comment]
I have it installed with

cordova 8
cordova-android 6.4.0

**Comment by amanpatel1449** [comment]
@sinedied , @cnttech  I have installed it with Cordova 8.0.0 and android 6.3.0.
Can you downgrade your android version and check it?

**Comment by sinedied** [comment]
Yes, it seems more related to the `cordova-android` upgrade than the cordova version, I'll rename the issue.
