### ISSUE TITLE
Getting error on some LG phones.

### ISSUE THREAD

**Issue by hdezela** [homerours/cordova-music-controls-plugin#20]
This is the error reported:

`java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.content.ComponentName.getPackageName()' on a null object reference
at android.media.AudioManager.registerMediaButtonIntent(AudioManager.java:2542)
at android.media.AudioManager.registerMediaButtonEventReceiver(AudioManager.java:2534)
at com.homerours.musiccontrols.MusicControls.registerMediaButtonEvent(MusicControls.java:49)
at com.homerours.musiccontrols.MusicControls.initialize(MusicControls.java:69)
at org.apache.cordova.CordovaPlugin.privateInitialize(CordovaPlugin.java:54)
at org.apache.cordova.PluginManager.getPlugin(PluginManager.java:169)
at org.apache.cordova.PluginManager.exec(PluginManager.java:120)
at org.apache.cordova.CordovaBridge.jsExec(CordovaBridge.java:59)
at org.apache.cordova.engine.SystemExposedJsApi.exec(SystemExposedJsApi.java:41)
at org.chromium.base.SystemMessageHandler.nativeDoRunLoopOnce(Native Method)
at org.chromium.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:37)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.os.HandlerThread.run(HandlerThread.java:61)`

I have absolutely no idea what that means...

**Comment by homerours** [comment]
Thank you for reporting this issue. It looks like the error comes from the "interception" of the media button (= headset button) click. You can comment the following lines in [MusicControls.java](https://github.com/homerours/cordova-music-controls-plugin/blob/master/src/android/MusicControls.java) to disable this feature:

- [lines 65-69](https://github.com/homerours/cordova-music-controls-plugin/blob/master/src/android/MusicControls.java#L65-L69)
- [line 49](https://github.com/homerours/cordova-music-controls-plugin/blob/master/src/android/MusicControls.java#L49)
- [line 52](https://github.com/homerours/cordova-music-controls-plugin/blob/master/src/android/MusicControls.java#L52)

I hope that it will fix the issue.

**Comment by hdezela** [comment]
Yup, that was it exactly...thank you for the speedy fix, you're awesome!
